### ISSUE TITLE
实测跟石像鬼严重冲突

### ISSUE THREAD

**Issue by cpexplorer** [infinet/dnsmasq#10]
石像鬼qos一开，wifi就会无限断线重启。
openwrt: cc 15.05.1 最新
石像鬼：1.9.2 最新
dnsmasq-fastlookup：2.77test4 最新commit

**Comment by cokebar** [comment]
LEDE无问题。cc别用2.77test4

**Comment by infinet** [comment]
石像鬼没用过，无法debug。

**Comment by cpexplorer** [comment]
换成2.72-5 fastlookup 也同样有这个问题 @cokebar 
大大如果愿意debug的话，我可以编译个带gargoyle和luci面板的固件给你测试看看 @infinet ；不开石像鬼的话一切都好，一开就无线就无限死掉重启
