### ISSUE TITLE
开启缓存时 --proxy-dnssec 仅作用于首次查询

### ISSUE THREAD

**Issue by quchao** [infinet/dnsmasq#12]
**分支：**
v2.77test4

**复现场景：**
当 `--cache-size` 大于 0 且开启 `--proxy-dnssec` ，
upstream 已选择支持 DNSSEC 的公共服务（如 8888 ），
首次查询 paypal.com 等域名有 RRSIG 记录，
第二次查询时则没有。

**规避方法：**
关闭缓存，即将 `--cache-size` 设为 `0` 。

**Comment by infinet** [comment]
如需DNSSEC，请用官方最新版本。
