### ISSUE TITLE
v2ray每天不定时断线

### ISSUE THREAD

**Issue by bin129** [infinet/dnsmasq#21]
我通过光猫桥接到软路由pppoe上网，用openwrt的v2ray翻墙，国内连接都正常，服务器端使用动态端口，但每天无数次国外断线，是什么原因？

**Comment by bin129** [comment]
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: BusyBox v1.30.0 () multi-call binary.
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]:
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: Usage: basename FILE [SUFFIX]
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]:
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: Strip directory path and .SUFFIX from FILE
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: BusyBox v1.30.0 () multi-call binary.
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]:
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: Usage: basename FILE [SUFFIX]
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]:
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: Strip directory path and .SUFFIX from FILE
Fri Jan 25 11:14:23 2019 user.notice nft-qos-dynamic: ACTION=update, MACADDR=f4:5c:89:98:67:91, IPADDR=192.168.2.147, HOSTNAME=bin
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: BusyBox v1.30.0 () multi-call binary.
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]:
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: Usage: basename FILE [SUFFIX]
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]:
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: Strip directory path and .SUFFIX from FILE
Fri Jan 25 11:14:23 2019 user.notice nft-qos-monitor: ACTION=update, MACADDR=20:ab:37:98:35:23, IPADDR=192.168.2.180, HOSTNAME=iPhone
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: BusyBox v1.30.0 () multi-call binary.
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]:
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: Usage: basename FILE [SUFFIX]
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]:
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: Strip directory path and .SUFFIX from FILE
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: BusyBox v1.30.0 () multi-call binary.
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]:
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: Usage: basename FILE [SUFFIX]
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]:
系统日志：
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: Strip directory path and .SUFFIX from FILE
Fri Jan 25 11:14:23 2019 user.notice nft-qos-dynamic: ACTION=update, MACADDR=20:ab:37:98:35:23, IPADDR=192.168.2.180, HOSTNAME=iPhone
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: BusyBox v1.30.0 () multi-call binary.
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]:
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: Usage: basename FILE [SUFFIX]
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]:
Fri Jan 25 11:14:23 2019 daemon.debug dnsmasq-script[31492]: Strip directory path and .SUFFIX from FILE
Fri Jan 25 11:14:23 2019 user.notice nft-qos-monitor: ACTION=update, MACADDR=08:62:66:91:70:60, IPADDR=192.168.2.157, HOSTNAME=
Fri Jan 25 11:14:24 2019 daemon.debug dnsmasq-script[31492]: BusyBox v1.30.0 () multi-call binary.

**Comment by bin129** [comment]
在客户端把加密协议由auto改成128.cfb以后稍微稳定些，但还是会断线。运行root@Openwrt:~# dnsmasq -test

dnsmasq: failed to create listening socket for port 53: Address in use
这需要怎么办？

**Comment by infinet** [comment]
“dnsmasq: failed to create listening socket for port 53: Address in use”多半是因为dnsmasq已经在运行。

另外，v2ray和dnsmasq无关。
