### ISSUE TITLE
dnsmasq: failed to create listening socket for port 53: Permission denied

### ISSUE THREAD

**Issue by wxf26054** [infinet/dnsmasq#22]
dnsmasq: failed to create listening socket for port 53: Permission denied

**Comment by infinet** [comment]
Check your system, either there is another dnsmasq running, or another program is listening on port 53.

**Comment by wxf26054** [comment]
no, there is no other software using port 53. And all the configuration file is set permission to 777. And I'm using superuser account.

**Comment by infinet** [comment]
can you compare it with original dnsmasq? Does the orginal dnsmasq run without problem?

**Comment by wxf26054** [comment]
My dnsmasq is the original dnsmasq install by  apt
