### ISSUE TITLE
lede下编译出错

### ISSUE THREAD

**Issue by cpexplorer** [infinet/dnsmasq#7]
lede :17.01.0
编译的版本：2.77 test4
错误提示：
`mipsel-openwrt-linux-musl-gcc -L/home/acm-zjc/build/lede_17.01.0_d1/staging_dir/target-mipsel_24kc_musl-1.1.16/usr/lib -L/home/acm-zjc/build/lede_17.01.0_d1/staging_dir/target-mipsel_24kc_musl-1.1.16/lib -L/home/acm-zjc/build/lede_17.01.0_d1/staging_dir/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/usr/lib -L/home/acm-zjc/build/lede_17.01.0_d1/staging_dir/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/lib -znow -zrelro -Wl,--gc-sections -o dnsmasq cache.o rfc1035.o util.o option.o forward.o network.o dnsmasq.o dhcp.o lease.o rfc2131.o netlink.o dbus.o bpf.o helper.o tftp.o log.o conntrack.o dhcp6.o rfc3315.o dhcp-common.o outpacket.o radv.o slaac.o auth.o ipset.o domain.o dnssec.o blockdata.o tables.o loop.o inotify.o poll.o rrfilter.o edns0.o arp.o -L/home/acm-zjc/build/lede_17.01.0_d1/staging_dir/target-mipsel_24kc_musl-1.1.16/usr/lib -lnetfilter_conntrack -lnfnetlink    -L/home/acm-zjc/build/lede_17.01.0_d1/staging_dir/target-mipsel_24kc_musl-1.1.16/usr/lib -lnettle -lhogweed -lgmp
/home/acm-zjc/build/lede_17.01.0_d1/staging_dir/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/lib/gcc/mipsel-openwrt-linux-musl/5.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: copy reloc against protected `__stack_chk_guard' is dangerous
option.o: In function `$L1637':
option.c:(.text.one_opt+0x12f8): undefined reference to `htree_new_node'
option.c:(.text.one_opt+0x1340): undefined reference to `domain_find_or_add'
option.c:(.text.one_opt+0x138c): undefined reference to `lookup_or_install_new_server'
option.c:(.text.one_opt+0x15c0): undefined reference to `htree_new_node'
option.c:(.text.one_opt+0x15d6): undefined reference to `htree_new_node'
option.c:(.text.one_opt+0x15ee): undefined reference to `htree_find_or_add'
option.c:(.text.one_opt+0x161a): undefined reference to `domain_find_or_add'
forward.o: In function `search_servers':
forward.c:(.text.search_servers+0x24): undefined reference to `domain_match'
forward.o: In function `process_reply':
forward.c:(.text.process_reply+0x2c): undefined reference to `domain_match'
collect2: error: ld returned 1 exit status
make[4]: *** [dnsmasq] Error 1
make[4]: Leaving directory `/home/acm-zjc/build/lede_17.01.0_d1/build_dir/target-mipsel_24kc_musl-1.1.16/dnsmasq-full/dnsmasq-2.77/src'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/acm-zjc/build/lede_17.01.0_d1/build_dir/target-mipsel_24kc_musl-1.1.16/dnsmasq-full/dnsmasq-2.77'
make[2]: *** [/home/acm-zjc/build/lede_17.01.0_d1/build_dir/target-mipsel_24kc_musl-1.1.16/dnsmasq-full/dnsmasq-2.77/.built] Error 2
make[2]: Leaving directory `/home/acm-zjc/build/lede_17.01.0_d1/package/network/services/dnsmasq'
make[1]: *** [package/network/services/dnsmasq/compile] Error 2
make[1]: Leaving directory `/home/acm-zjc/build/lede_17.01.0_d1'
make: *** [package/network/services/dnsmasq/compile] Error 2`

**Comment by infinet** [comment]
fixed.
